openapi: 3.0.0
info:
  title: 扫描二维码
  version: 1.0.0
  description: 解析二维码中的内容

servers:
  - url: https://open.cli.im/api/v1

paths:
  /qrcode/scan_url:
    post:
      summary: 扫描二维码
      description: 从给定的 URL 扫描二维码并返回二维码的内容。
      operationId: scanQRCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  description: 需要扫描的二维码图片的 URL
              required:
                - url
      responses:
        '200':
          description: 成功响应，包含二维码内容
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 响应的状态代码, 0表示成功
                    example: 0
                  message:
                    type: string
                    description: 响应的消息
                    example: ok
                  data:
                    type: object
                    properties:
                      content:
                        type: string
                        description: 从二维码中提取的内容
                        example: "https://cli.im"
                      provider:
                        type: string
                        description: 二维码URL服务商
                        example: "caoliao"
                        enum:
                          - Alipay
                          - WechatPay
                          - WechatOfficialAccountPost
                          - JD
                          - Caoliao
                          - Other
      security:
        - bearerAuth: [ ]
  /qrcode/read_markdown:
    post:
      summary: 读取活码内容
      description: 从活码读取信息并以指定的格式返回
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                qrcodeUrl:
                  type: string
                  description: 活码URL
                  example: https://qr61.cn/xxx/yyy
              required:
                - qrcodeUrl
                - format
      responses:
        '200':
          description: 成功响应
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ---
                  标题：Hello World
                  二维码URL: https://qr61.cn/xxx/yyy

                  ---

                  # Hello World

                  Foo Bar
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
  /qrcode/read_json:
    post:
      summary: 读取活码内容
      description: 从活码读取信息并以指定的格式返回
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                qrcodeUrl:
                  type: string
                  description: 活码URL
                  example: https://qr61.cn/xxx/yyy
              required:
                - qrcodeUrl
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 状态码, 0表示成功, 其他表示失败
                    example: 0
                  message:
                    type: string
                    description: 状态消息, 成功时为"ok", 失败时为错误消息
                    example: ok
                  data:
                    type: object
                    properties:
                      meta:
                        type: object
                        properties:
                          url:
                            type: string
                            description: 活码URL
                          title:
                            type: string
                            description: 活码名称
                          orgCode:
                            type: string
                            description: 企业ID
                          coding:
                            type: string
                            description: 活码编号(URL Path的最后一部分)
                      contents:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                              enum: [text, image, audio, video, contact, file]
                              description: 模块类型
                            text:
                              type: object
                              properties:
                                value:
                                  type: string
                                  description: 文本内容
                            image:
                              type: object
                              properties:
                                items:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      url:
                                        type: string
                                        description: 图片URL
                            audio:
                              type: object
                              properties:
                                url:
                                  type: string
                                  description: 音频URL
                                title:
                                  type: string
                                  description: 音频名称
                            video:
                              type: object
                              properties:
                                url:
                                  type: string
                                  description: 视频URL
                                title:
                                  type: string
                                  description: 视频标题
                                coverUrl:
                                  type: string
                                  description: 视频封面
                            contact:
                              type: object
                              properties:
                                wechatName:
                                  type: string
                                  description: 微信名称
                                phone:
                                  type: string
                                  description: 电话
                                email:
                                  type: string
                                  description: 邮箱
                                address:
                                  type: string
                                  description: 地址
                                workTime:
                                  type: string
                                  description: 工作时间
                            file:
                              type: object
                              properties:
                                title:
                                  type: string
                                  description: 文件名
                                url:
                                  type: string
                                  description: 文件URL
                      states:
                        type: array
                        description: 活码的状态列表
                        items:
                          type: object
                          properties:
                            serialNumber:
                              type: string
                              description: 状态编号
                            title:
                              type: string
                              description: 状态标题
                            value:
                              type: string
                              description: 状态值
                            valueID:
                              type: string
                              description: 状态值ID
                      forms:
                        type: array
                        description: 活码关联的表单列表
                        items:
                          type: object
                          properties:
                            serialNumber:
                              type: string
                              description: 表单编号
                            title:
                              type: string
                              description: 表单标题
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
  /forms/get_data:
    post:
      summary: 获取表单数据
      description: 根据二维码URL、表单ID和时间范围获取表单数据列表
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                qrCodeUrl:
                  type: string
                  description: 二维码URL
                  example: 'https://qr61.cn/xxx/yyy'
                formSerialNumber:
                  type: string
                  description: 表单编号
                  example: 'L101'
                startTime:
                  type: string
                  description: 开始时间
                  format: date-time
                  example: '2025-01-01 00:00:00'
                endTime:
                  type: string
                  description: 结束时间
                  format: date-time
                  example: '2025-01-31 00:00:00'
                pageToken:
                  type: string
                  description: 分页标记
                  example: 'd29ybGQ='
              required:
                - qrCodeUrl
                - formSerialNumber
      responses:
        '200':
          description: 成功获取表单数据
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 状态码，0表示成功，其他表示失败
                  message:
                    type: string
                    description: 状态消息，成功时为空，失败时为错误消息
                  data:
                    type: object
                    properties:
                      total:
                        type: integer
                        description: 数据总数
                      list:
                        type: array
                        description: 数据列表
                        items:
                          type: object
                          properties:
                            serialNumber:
                              type: string
                              description: 数据编号
                            qrCodeCoding:
                              type: string
                              description: 二维码Coding
                            formSerialNumber:
                              type: string
                              description: 表单编号
                            addTime:
                              type: string
                              description: 添加时间
                              format: date-time
                            recorder:
                              type: string
                              description: 表单填写人
                            fields:
                              type: array
                              description: 表单字段列表
                              items:
                                $ref: '#/components/schemas/FormField'
                      nextPageToken:
                        type: string
                        description: 下一页的分页标记
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    FormField:
      type: object
      properties:
        id:
          type: integer
          description: 字段ID
        groupId:
          type: integer
          description: 字段组ID
        type:
          type: string
          description: 字段类型
          enum: [
            'name', 'tel', 'recorder', 'identity', 'job_number', 
            'carnumber', 'sex', 'text', 'textarea', 'number', 
            'checklist', 'matrix', 'dynamic_matrix', 'date', 'time',
            'radio', 'checkbox', 'address', 'owner_address', 
            'customer_name', 'customer_mobile', 'chained_selects',
            'signature', 'image', 'video', 'audio', 'file', 'description'
          ]
        title:
          type: string
          description: 字段标题
        nameValue:
          $ref: '#/components/schemas/NameValue'
        telValue:
          $ref: '#/components/schemas/TelValue'
        recorderValue:
          $ref: '#/components/schemas/RecorderValue'
        identityValue:
          $ref: '#/components/schemas/IdentityValue'
        jobNumberValue:
          $ref: '#/components/schemas/JobNumberValue'
        carNumberValue:
          $ref: '#/components/schemas/CarNumberValue'
        sexValue:
          $ref: '#/components/schemas/SexValue'
        textValue:
          $ref: '#/components/schemas/TextValue'
        textareaValue:
          $ref: '#/components/schemas/TextareaValue'
        numberValue:
          $ref: '#/components/schemas/NumberValue'
        checkListValue:
          $ref: '#/components/schemas/CheckListValue'
        matrixValue:
          $ref: '#/components/schemas/MatrixValue'
        dynamicMatrixValue:
          $ref: '#/components/schemas/DynamicMatrixValue'
        dateValue:
          $ref: '#/components/schemas/DateValue'
        timeValue:
          $ref: '#/components/schemas/TimeValue'
        radioValue:
          $ref: '#/components/schemas/RadioValue'
        checkboxValue:
          $ref: '#/components/schemas/CheckboxValue'
        addressValue:
          $ref: '#/components/schemas/AddressValue'
        ownerAddressValue:
          $ref: '#/components/schemas/OwnerAddressValue'
        customerNameValue:
          $ref: '#/components/schemas/CustomerNameValue'
        customerMobileValue:
          $ref: '#/components/schemas/CustomerMobileValue'
        signatureValue:
          $ref: '#/components/schemas/SignatureValue'
        imageValue:
          $ref: '#/components/schemas/ImageValue'
        videoValue:
          $ref: '#/components/schemas/VideoValue'
        audioValue:
          $ref: '#/components/schemas/AudioValue'
        fileValue:
          $ref: '#/components/schemas/FileValue'

    # 填写人姓名
    NameValue:
      type: object
      properties:
        value:
          type: string
          description: 姓名字符串值

    # 填写人手机号
    TelValue:
      type: object
      properties:
        value:
          type: string
          description: 手机号字符串值

    # 填写人微信名
    RecorderValue:
      type: object
      properties:
        value:
          type: string
          description: 填表人微信名字符串值

    # 身份证号
    IdentityValue:
      type: object
      properties:
        value:
          type: string
          description: 身份证号字符串值

    # 工号
    JobNumberValue:
      type: object
      properties:
        value:
          type: string
          description: 工号字符串值

    # 车牌号
    CarNumberValue:
      type: object
      properties:
        value:
          type: string
          description: 车牌号字符串值

    # 性别
    SexValue:
      type: object
      properties:
        value:
          type: string
          description: 性别字符串值
          enum: ['男', '女']

    # 文本
    TextValue:
      type: object
      properties:
        value:
          type: string
          description: 文本字符串值

    # 多行文本
    TextareaValue:
      type: object
      properties:
        value:
          type: string
          description: 多行文本字符串值

    # 数字
    NumberValue:
      type: object
      properties:
        value:
          type: string
          description: 数字的字符串值（带单位）

    # 检查项
    CheckListValue:
      type: object
      properties:
        checkValues:
          type: array
          items:
            type: object
            properties:
              optionId:
                type: integer
                description: 检查项的选项ID
              title:
                type: string
                description: 检查项的选项名称
              value:
                type: string
                description: 检查项是否被选中
                enum: ['0', '1']

    # 表格组件
    MatrixValue:
      type: object
      properties:
        matrixValues:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
                description: 标题
              value:
                type: string
                description: 值

    # 动态表格组件
    DynamicMatrixValue:
      type: object
      properties:
        dynamicMatrixValues:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
                description: 标题
              value:
                type: string
                description: 值

    # 日期
    DateValue:
      type: object
      properties:
        value:
          type: string
          description: 日期字符串值

    # 时间
    TimeValue:
      type: object
      properties:
        value:
          type: string
          description: 时间字符串值

    # 单选
    RadioValue:
      type: object
      properties:
        value:
          type: string
          description: 选项的值

    # 多选
    CheckboxValue:
      type: object
      properties:
        values:
          type: array
          items:
            type: string
          description: 多选的值数组

    # 定位组件
    AddressValue:
      type: object
      properties:
        value:
          type: string
          description: 定位字符串值

    # 地址组件
    OwnerAddressValue:
      type: object
      properties:
        value:
          type: string
          description: 地址字符串值

    # 客户姓名
    CustomerNameValue:
      type: object
      properties:
        value:
          type: string
          description: 姓名字符串值

    # 客户手机号
    CustomerMobileValue:
      type: object
      properties:
        value:
          type: string
          description: 手机号字符串值

    # 签名
    SignatureValue:
      type: object
      description: 签名字段值

    # 图像
    ImageValue:
      type: object
      properties:
        images:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                description: 图像的URL

    # 视频
    VideoValue:
      type: object
      properties:
        videos:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                description: 视频的URL
              title:
                type: string
                description: 视频的名称

    # 音频
    AudioValue:
      type: object
      properties:
        audios:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                description: 音频的URL
              title:
                type: string
                description: 音频的名称

    # 文件
    FileValue:
      type: object
      properties:
        files:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                description: 文件的URL
              title:
                type: string
                description: 文件的名称
